//
// Created by erik on 2020-05-10.
//

#ifndef COMPETITIVE_PROGRAMMING_4A_WATERMELON_H
#define COMPETITIVE_PROGRAMMING_4A_WATERMELON_H
void watermelon ();
#endif //COMPETITIVE_PROGRAMMING_4A_WATERMELON_H
