//
// Created by erik on 2020-05-10.
//

#ifndef COMPETETIVE_PROGRAMMING_4A_WATERMELON_H
#define COMPETETIVE_PROGRAMMING_4A_WATERMELON_H
void watermelon ();
#endif //COMPETETIVE_PROGRAMMING_4A_WATERMELON_H
