
#include "vector"

#ifndef COMPETITIVE_PROGRAMMING_1402_REDUCING_DISHES_H
#define COMPETITIVE_PROGRAMMING_1402_REDUCING_DISHES_H
int maxSatisfaction(std::vector<int>& satisfaction);
#endif //COMPETITIVE_PROGRAMMING_1402_REDUCING_DISHES_H
